### ISSUE TITLE
v1 tag is not updated

### ISSUE THREAD

**Issue by ellull** [esphome/build-action#18]
Hello, I'm using your Github action to build an ESPHome firmware in a workflow like this:
```
      - name: Build firmware
        uses: esphome/build-action@v1
        id: firmware-build
        with:
          yaml_file: ${{ matrix.file }}
```
And I noticed these warnings in the workflow execution:
> Build firmware from firmware/fan-controller-v1.yaml
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Then I checked the source code of the action (in this repository) and I found that the action was not using the old set-output commands. Next I read the release notes and found that this issue was fixed in v1.7.0.

Then I realized that the v1 tag is still pointing to the same commit as v1.5.0, and that is the reason why I still get the warnings although the issue was fixed.

I think the v1 tag should point to the last release of v1.x.y so people like me can use the v1 tag and their workflows will always use the latest version the new releases as they might happen without having to update their workflows.

Please can you consider updating the v1 tag to point to the latest v1.x.y release? You could use the haya14busa/action-update-semver action, or similar, to automate it every time a new version is released.

For the moment I will change my workflow to use the v1.8.0 tag.

And thank you very much for all your work.

**Comment by barndawgie** [comment]
@jesserockz or @vidplace7 Would be great to get this resolved - I hope it's just a matter of updating the v1 tag.

**Comment by jesserockz** [comment]
Apologies for the delay, I have updated the tags now and will try to keep on top of it in future releases
