### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by lanwin** [esphome/build-action#23]
I use this action to the build of my custom ESPHome component.

https://github.com/lanwin/esphome_samsung_ac/blob/main/.github/workflows/build.yml

So far this works. But I see only the exection command of docker. My wish would be to also have a verbose mode where I can see the build output within the Github Workflow log.

**Comment by jesserockz** [comment]
The build logs are there, just collapsed under a log group, see https://github.com/esphome/firmware/actions/runs/7967688919/job/21750810217#step:3:725

![image](https://github.com/esphome/build-action/assets/3060199/c8489d49-edc7-487c-a7a4-83bf1ee19130)
